// This file is auto-generated by @hey-api/openapi-ts

import { type Options, createClient, createConfig } from '@hey-api/client-axios'
import type {
  AuthCallbackAuthCallbackGetError,
  AuthCallbackAuthCallbackGetResponse,
  AuthSchwabAuthSchwabGetError,
  AuthSchwabAuthSchwabGetResponse,
  GetHistoryDailyPriceEquityHistoryDailyGetData,
  GetHistoryDailyPriceEquityHistoryDailyGetError,
  GetHistoryDailyPriceEquityHistoryDailyGetResponse,
  GetInfoEquityInfoGetData,
  GetInfoEquityInfoGetError,
  GetInfoEquityInfoGetResponse,
  GetPositionsAccountPositionsGetError,
  GetPositionsAccountPositionsGetResponse,
  GetTransactionsAccountTransactionsGetError,
  GetTransactionsAccountTransactionsGetResponse,
  GetWeeklyResistanceMlWeeklyResistanceGetData,
  GetWeeklyResistanceMlWeeklyResistanceGetError,
  GetWeeklyResistanceMlWeeklyResistanceGetResponse,
  RestartStreamEndpointRestartStreamPostError,
  RestartStreamEndpointRestartStreamPostResponse,
} from './types.gen'

export const client = createClient(
  createConfig({
    baseURL: process.env.NEXT_PUBLIC_BACKEND_URL,
  }),
)

/**
 * Get Positions
 */
export const getPositionsAccountPositionsGet = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetPositionsAccountPositionsGetResponse,
    GetPositionsAccountPositionsGetError,
    ThrowOnError
  >({
    ...options,
    url: '/account/positions',
  })
}

/**
 * Get Transactions
 */
export const getTransactionsAccountTransactionsGet = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetTransactionsAccountTransactionsGetResponse,
    GetTransactionsAccountTransactionsGetError,
    ThrowOnError
  >({
    ...options,
    url: '/account/transactions',
  })
}

/**
 * Auth Schwab
 */
export const authSchwabAuthSchwabGet = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    AuthSchwabAuthSchwabGetResponse,
    AuthSchwabAuthSchwabGetError,
    ThrowOnError
  >({
    ...options,
    url: '/auth/schwab',
  })
}

/**
 * Auth Callback
 */
export const authCallbackAuthCallbackGet = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    AuthCallbackAuthCallbackGetResponse,
    AuthCallbackAuthCallbackGetError,
    ThrowOnError
  >({
    ...options,
    url: '/auth/callback',
  })
}

/**
 * Get Info
 */
export const getInfoEquityInfoGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetInfoEquityInfoGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetInfoEquityInfoGetResponse,
    GetInfoEquityInfoGetError,
    ThrowOnError
  >({
    ...options,
    url: '/equity/info',
  })
}

/**
 * Get History Daily Price
 */
export const getHistoryDailyPriceEquityHistoryDailyGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetHistoryDailyPriceEquityHistoryDailyGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetHistoryDailyPriceEquityHistoryDailyGetResponse,
    GetHistoryDailyPriceEquityHistoryDailyGetError,
    ThrowOnError
  >({
    ...options,
    url: '/equity/history/daily',
  })
}

/**
 * Get Weekly Resistance
 */
export const getWeeklyResistanceMlWeeklyResistanceGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetWeeklyResistanceMlWeeklyResistanceGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetWeeklyResistanceMlWeeklyResistanceGetResponse,
    GetWeeklyResistanceMlWeeklyResistanceGetError,
    ThrowOnError
  >({
    ...options,
    url: '/ml/weekly-resistance',
  })
}

/**
 * Restart Stream Endpoint
 */
export const restartStreamEndpointRestartStreamPost = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    RestartStreamEndpointRestartStreamPostResponse,
    RestartStreamEndpointRestartStreamPostError,
    ThrowOnError
  >({
    ...options,
    url: '/restart-stream',
  })
}
