// This file is auto-generated by @hey-api/openapi-ts

export type AccountAPIOptionDeliverable = {
  symbol?: string | null
  deliverableUnits?: number | null
  apiCurrencyType?: ApiCurrencyType | null
  assetType?: axiom__schwab_models_account__AssetType | null
}

export type AccountCashEquivalent = {
  assetType: 'CASH_EQUIVALENT'
  cusip?: string | null
  symbol?: string | null
  description?: string | null
  instrumentId?: number | null
  netChange?: number | null
  type?: Type11 | null
}

export type AccountCollectiveInvestment = {
  assetType: 'COLLECTIVE_INVESTMENT'
  cusip?: string | null
  symbol?: string | null
  description?: string | null
  instrumentId?: number | null
  netChange?: number | null
  type?: Type2 | null
}

export type AccountEquity = {
  assetType: 'EQUITY'
  cusip?: string | null
  symbol?: string | null
  description?: string | null
  instrumentId?: number | null
  netChange?: number | null
}

export type AccountFixedIncome = {
  assetType: 'FIXED_INCOME'
  cusip?: string | null
  symbol?: string | null
  description?: string | null
  instrumentId?: number | null
  netChange?: number | null
  maturityDate?: string | null
  factor?: number | null
  variableRate?: number | null
}

export type AccountMutualFund = {
  assetType: 'MUTUAL_FUND'
  cusip?: string | null
  symbol?: string | null
  description?: string | null
  instrumentId?: number | null
  netChange?: number | null
}

export type AccountOption = {
  assetType: 'OPTION'
  cusip?: string | null
  symbol?: string | null
  description?: string | null
  instrumentId?: number | null
  netChange?: number | null
  optionDeliverables?: Array<AccountAPIOptionDeliverable> | null
  putCall?: PutCall | null
  optionMultiplier?: number | null
  type?: Type12 | null
  underlyingSymbol?: string | null
}

export type AccountsInstrument =
  | AccountCashEquivalent
  | AccountEquity
  | AccountFixedIncome
  | AccountMutualFund
  | AccountOption
  | AccountCollectiveInvestment

export type ActivityType1 =
  | 'ACTIVITY_CORRECTION'
  | 'EXECUTION'
  | 'ORDER_ACTION'
  | 'TRANSFER'
  | 'UNKNOWN'

export type ApiCurrencyType = 'USD' | 'CAD' | 'EUR' | 'JPY'

export type Bond = {
  cusip?: string | null
  symbol?: string | null
  description?: string | null
  exchange?: string | null
  assetType?: axiom__schwab_models__AssetType | null
  bondFactor?: string | null
  bondMultiplier?: string | null
  bondPrice?: number | null
  type?: Type | null
}

export type Candle = {
  close?: number | null
  datetime?: number | null
  datetimeISO8601?: string | null
  high?: number | null
  low?: number | null
  open?: number | null
  volume?: number | null
}

export type CandleList = {
  candles?: Array<Candle> | null
  empty?: boolean | null
  previousClose?: number | null
  previousCloseDate?: number | null
  previousCloseDateISO8601?: string | null
  symbol?: string | null
}

export type CollectiveInvestment = {
  assetType: 'COLLECTIVE_INVESTMENT'
  cusip?: string | null
  symbol?: string | null
  description?: string | null
  instrumentId?: number | null
  netChange?: number | null
  type?: Type2 | null
}

export type Currency = {
  assetType: 'CURRENCY'
  cusip?: string | null
  symbol?: string | null
  description?: string | null
  instrumentId?: number | null
  netChange?: number | null
}

export type FeeType1 =
  | 'COMMISSION'
  | 'SEC_FEE'
  | 'STR_FEE'
  | 'R_FEE'
  | 'CDSC_FEE'
  | 'OPT_REG_FEE'
  | 'ADDITIONAL_FEE'
  | 'MISCELLANEOUS_FEE'
  | 'FUTURES_EXCHANGE_FEE'
  | 'LOW_PROCEEDS_COMMISSION'
  | 'BASE_CHARGE'
  | 'GENERAL_CHARGE'
  | 'GST_FEE'
  | 'TAF_FEE'
  | 'INDEX_OPTION_FEE'
  | 'UNKNOWN'

export type Forex = {
  assetType: 'FOREX'
  cusip?: string | null
  symbol?: string | null
  description?: string | null
  instrumentId?: number | null
  netChange?: number | null
  type?: Type5 | null
  baseCurrency?: Currency | null
  counterCurrency?: Currency | null
}

export type FundamentalInst = {
  symbol?: string | null
  high52?: number | null
  low52?: number | null
  dividendAmount?: number | null
  dividendYield?: number | null
  dividendDate?: string | null
  peRatio?: number | null
  pegRatio?: number | null
  pbRatio?: number | null
  prRatio?: number | null
  pcfRatio?: number | null
  grossMarginTTM?: number | null
  grossMarginMRQ?: number | null
  netProfitMarginTTM?: number | null
  netProfitMarginMRQ?: number | null
  operatingMarginTTM?: number | null
  operatingMarginMRQ?: number | null
  returnOnEquity?: number | null
  returnOnAssets?: number | null
  returnOnInvestment?: number | null
  quickRatio?: number | null
  currentRatio?: number | null
  interestCoverage?: number | null
  totalDebtToCapital?: number | null
  ltDebtToEquity?: number | null
  totalDebtToEquity?: number | null
  epsTTM?: number | null
  epsChangePercentTTM?: number | null
  epsChangeYear?: number | null
  epsChange?: number | null
  revChangeYear?: number | null
  revChangeTTM?: number | null
  revChangeIn?: number | null
  sharesOutstanding?: number | null
  marketCapFloat?: number | null
  marketCap?: number | null
  bookValuePerShare?: number | null
  shortIntToFloat?: number | null
  shortIntDayToCover?: number | null
  divGrowthRate3Year?: number | null
  dividendPayAmount?: number | null
  dividendPayDate?: string | null
  beta?: number | null
  vol1DayAvg?: number | null
  vol10DayAvg?: number | null
  vol3MonthAvg?: number | null
  avg10DaysVolume?: number | null
  avg1DayVolume?: number | null
  avg3MonthVolume?: number | null
  declarationDate?: string | null
  dividendFreq?: number | null
  eps?: number | null
  corpactionDate?: string | null
  dtnVolume?: number | null
  nextDividendPayDate?: string | null
  nextDividendDate?: string | null
  fundLeverageFactor?: number | null
  fundStrategy?: string | null
}

export type Future = {
  activeContract?: boolean | null
  type?: Type6 | null
  expirationDate?: string | null
  lastTradingDate?: string | null
  firstNoticeDate?: string | null
  multiplier?: number | null
  assetType: 'FUTURE'
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type Index = {
  activeContract?: boolean | null
  type?: Type7 | null
  assetType: 'INDEX'
}

export type Instrument = {
  cusip?: string | null
  symbol?: string | null
  description?: string | null
  exchange?: string | null
  assetType?: axiom__schwab_models__AssetType | null
  type?: Type | null
}

export type InstrumentResponse = {
  cusip?: string | null
  symbol?: string | null
  description?: string | null
  exchange?: string | null
  assetType?: axiom__schwab_models__AssetType | null
  bondFactor?: string | null
  bondMultiplier?: string | null
  bondPrice?: number | null
  fundamental?: FundamentalInst | null
  instrumentInfo?: Instrument | null
  bondInstrumentInfo?: Bond | null
  type?: Type | null
}

export type Position = {
  shortQuantity?: number | null
  averagePrice?: number | null
  currentDayProfitLoss?: number | null
  currentDayProfitLossPercentage?: number | null
  longQuantity?: number | null
  settledLongQuantity?: number | null
  settledShortQuantity?: number | null
  agedQuantity?: number | null
  instrument?: AccountsInstrument | null
  marketValue?: number | null
  maintenanceRequirement?: number | null
  averageLongPrice?: number | null
  averageShortPrice?: number | null
  taxLotAverageLongPrice?: number | null
  taxLotAverageShortPrice?: number | null
  longOpenProfitLoss?: number | null
  shortOpenProfitLoss?: number | null
  previousSessionLongQuantity?: number | null
  previousSessionShortQuantity?: number | null
  currentDayCost?: number | null
}

export type PositionEffect1 = 'OPENING' | 'CLOSING' | 'AUTOMATIC' | 'UNKNOWN'

export type Product = {
  assetType: 'PRODUCT'
  cusip?: string | null
  symbol?: string | null
  description?: string | null
  instrumentId?: number | null
  netChange?: number | null
  type?: Type10 | null
}

export type PutCall = 'PUT' | 'CALL' | 'UNKNOWN'

export type Status1 = 'VALID' | 'INVALID' | 'PENDING' | 'UNKNOWN'

export type SubAccount = 'CASH' | 'MARGIN' | 'SHORT' | 'DIV' | 'INCOME' | 'UNKNOWN'

export type Transaction = {
  activityId?: number | null
  time?: string | null
  user?: UserDetails | null
  description?: string | null
  accountNumber?: string | null
  type?: TransactionType | null
  status?: Status1 | null
  subAccount?: SubAccount | null
  tradeDate?: string | null
  settlementDate?: string | null
  positionId?: number | null
  orderId?: number | null
  netAmount?: number | null
  activityType?: ActivityType1 | null
  transferItems?: Array<TransferItem> | null
}

export type TransactionAPIOptionDeliverable = {
  rootSymbol?: string | null
  strikePercent?: number | null
  deliverableNumber?: number | null
  deliverableUnits?: number | null
  deliverable?: TransactionInstrument | null
  assetType?: axiom__schwab_models_account__AssetType | null
}

export type TransactionCashEquivalent = {
  assetType: 'CASH_EQUIVALENT'
  cusip?: string | null
  symbol?: string | null
  description?: string | null
  instrumentId?: number | null
  netChange?: number | null
  type?: Type1 | null
}

export type TransactionEquity = {
  assetType: 'EQUITY'
  cusip?: string | null
  symbol?: string | null
  description?: string | null
  instrumentId?: number | null
  netChange?: number | null
  type?: Type3 | null
}

export type TransactionFixedIncome = {
  assetType: 'FIXED_INCOME'
  cusip?: string | null
  symbol?: string | null
  description?: string | null
  instrumentId?: number | null
  netChange?: number | null
  type?: Type4 | null
  maturityDate?: string | null
  factor?: number | null
  multiplier?: number | null
  variableRate?: number | null
}

export type TransactionInstrument =
  | TransactionCashEquivalent
  | CollectiveInvestment
  | Currency
  | TransactionEquity
  | TransactionFixedIncome
  | Forex
  | Future
  | Index
  | TransactionMutualFund
  | TransactionOption
  | Product

export type TransactionMutualFund = {
  assetType: 'MUTUAL_FUND'
  cusip?: string | null
  symbol?: string | null
  description?: string | null
  instrumentId?: number | null
  netChange?: number | null
  fundFamilyName?: string | null
  fundFamilySymbol?: string | null
  fundGroup?: string | null
  type?: Type8 | null
  exchangeCutoffTime?: string | null
  purchaseCutoffTime?: string | null
  redemptionCutoffTime?: string | null
}

export type TransactionOption = {
  assetType: 'OPTION'
  cusip?: string | null
  symbol?: string | null
  description?: string | null
  instrumentId?: number | null
  netChange?: number | null
  expirationDate?: string | null
  optionDeliverables?: Array<TransactionAPIOptionDeliverable> | null
  optionPremiumMultiplier?: number | null
  putCall?: PutCall | null
  strikePrice?: number | null
  type?: Type9 | null
  underlyingSymbol?: string | null
  underlyingCusip?: string | null
  deliverable?: TransactionInstrument | null
}

export type TransactionType =
  | 'TRADE'
  | 'RECEIVE_AND_DELIVER'
  | 'DIVIDEND_OR_INTEREST'
  | 'ACH_RECEIPT'
  | 'ACH_DISBURSEMENT'
  | 'CASH_RECEIPT'
  | 'CASH_DISBURSEMENT'
  | 'ELECTRONIC_FUND'
  | 'WIRE_OUT'
  | 'WIRE_IN'
  | 'JOURNAL'
  | 'MEMORANDUM'
  | 'MARGIN_CALL'
  | 'MONEY_MARKET'
  | 'SMA_ADJUSTMENT'

export type TransferItem = {
  instrument?: TransactionInstrument | null
  amount?: number | null
  cost?: number | null
  price?: number | null
  feeType?: FeeType1 | null
  positionEffect?: PositionEffect1 | null
}

export type Type =
  | 'BOND'
  | 'EQUITY'
  | 'ETF'
  | 'EXTENDED'
  | 'FOREX'
  | 'FUTURE'
  | 'FUTURE_OPTION'
  | 'FUNDAMENTAL'
  | 'INDEX'
  | 'INDICATOR'
  | 'MUTUAL_FUND'
  | 'OPTION'
  | 'UNKNOWN'

export type Type1 = 'SWEEP_VEHICLE' | 'SAVINGS' | 'MONEY_MARKET_FUND' | 'UNKNOWN'

export type Type10 = 'TBD' | 'UNKNOWN'

export type Type11 = 'SWEEP_VEHICLE' | 'SAVINGS' | 'MONEY_MARKET_FUND' | 'UNKNOWN'

export type Type12 = 'VANILLA' | 'BINARY' | 'BARRIER' | 'UNKNOWN'

export type Type13 = 'ADVISOR_USER' | 'BROKER_USER' | 'CLIENT_USER' | 'SYSTEM_USER' | 'UNKNOWN'

export type Type2 =
  | 'UNIT_INVESTMENT_TRUST'
  | 'EXCHANGE_TRADED_FUND'
  | 'CLOSED_END_FUND'
  | 'INDEX'
  | 'UNITS'

export type Type3 =
  | 'COMMON_STOCK'
  | 'PREFERRED_STOCK'
  | 'DEPOSITORY_RECEIPT'
  | 'PREFERRED_DEPOSITORY_RECEIPT'
  | 'RESTRICTED_STOCK'
  | 'COMPONENT_UNIT'
  | 'RIGHT'
  | 'WARRANT'
  | 'CONVERTIBLE_PREFERRED_STOCK'
  | 'CONVERTIBLE_STOCK'
  | 'LIMITED_PARTNERSHIP'
  | 'WHEN_ISSUED'
  | 'UNKNOWN'

export type Type4 =
  | 'BOND_UNIT'
  | 'CERTIFICATE_OF_DEPOSIT'
  | 'CONVERTIBLE_BOND'
  | 'COLLATERALIZED_MORTGAGE_OBLIGATION'
  | 'CORPORATE_BOND'
  | 'GOVERNMENT_MORTGAGE'
  | 'GNMA_BONDS'
  | 'MUNICIPAL_ASSESSMENT_DISTRICT'
  | 'MUNICIPAL_BOND'
  | 'OTHER_GOVERNMENT'
  | 'SHORT_TERM_PAPER'
  | 'US_TREASURY_BOND'
  | 'US_TREASURY_BILL'
  | 'US_TREASURY_NOTE'
  | 'US_TREASURY_ZERO_COUPON'
  | 'AGENCY_BOND'
  | 'WHEN_AS_AND_IF_ISSUED_BOND'
  | 'ASSET_BACKED_SECURITY'
  | 'UNKNOWN'

export type Type5 = 'STANDARD' | 'NBBO' | 'UNKNOWN'

export type Type6 = 'STANDARD' | 'UNKNOWN'

export type Type7 = 'BROAD_BASED' | 'NARROW_BASED' | 'UNKNOWN'

export type Type8 =
  | 'NOT_APPLICABLE'
  | 'OPEN_END_NON_TAXABLE'
  | 'OPEN_END_TAXABLE'
  | 'NO_LOAD_NON_TAXABLE'
  | 'NO_LOAD_TAXABLE'
  | 'UNKNOWN'

export type Type9 = 'VANILLA' | 'BINARY' | 'BARRIER' | 'UNKNOWN'

export type UserDetails = {
  cdDomainId?: string | null
  login?: string | null
  type?: Type13 | null
  userId?: number | null
  systemUserName?: string | null
  firstName?: string | null
  lastName?: string | null
  brokerRepCode?: string | null
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type axiom__schwab_models__AssetType =
  | 'BOND'
  | 'EQUITY'
  | 'ETF'
  | 'EXTENDED'
  | 'FOREX'
  | 'FUTURE'
  | 'FUTURE_OPTION'
  | 'FUNDAMENTAL'
  | 'INDEX'
  | 'INDICATOR'
  | 'MUTUAL_FUND'
  | 'OPTION'
  | 'UNKNOWN'

export type axiom__schwab_models_account__AssetType =
  | 'EQUITY'
  | 'MUTUAL_FUND'
  | 'OPTION'
  | 'FUTURE'
  | 'FOREX'
  | 'INDEX'
  | 'CASH_EQUIVALENT'
  | 'FIXED_INCOME'
  | 'PRODUCT'
  | 'CURRENCY'
  | 'COLLECTIVE_INVESTMENT'

export type GetPositionsAccountPositionsGetResponse = Array<Position>

export type GetPositionsAccountPositionsGetError = unknown

export type GetTransactionsAccountTransactionsGetResponse = Array<Transaction>

export type GetTransactionsAccountTransactionsGetError = unknown

export type AuthSchwabAuthSchwabGetResponse = unknown

export type AuthSchwabAuthSchwabGetError = unknown

export type AuthCallbackAuthCallbackGetResponse = unknown

export type AuthCallbackAuthCallbackGetError = unknown

export type GetInfoEquityInfoGetData = {
  query?: {
    symbol?: string
  }
}

export type GetInfoEquityInfoGetResponse = InstrumentResponse

export type GetInfoEquityInfoGetError = HTTPValidationError

export type GetHistoryDailyPriceEquityHistoryDailyGetData = {
  query?: {
    symbol?: string
  }
}

export type GetHistoryDailyPriceEquityHistoryDailyGetResponse = CandleList

export type GetHistoryDailyPriceEquityHistoryDailyGetError = HTTPValidationError

export type GetWeeklyResistanceMlWeeklyResistanceGetData = {
  query?: {
    symbol?: string
  }
}

export type GetWeeklyResistanceMlWeeklyResistanceGetResponse = unknown

export type GetWeeklyResistanceMlWeeklyResistanceGetError = HTTPValidationError

export type RestartStreamEndpointRestartStreamPostResponse = unknown

export type RestartStreamEndpointRestartStreamPostError = unknown
